# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f549161539bf1b65b19f0f9d075ea07598fe3cf606c27453239ec29b9a65cd26395cd3572d37f78e8c4e3af6a9a787c359c796d7e3458950bb1c43c82e012b52

test:
  secret_key_base: 1449c794dd75801834f1e3f1d2207256bc3f6e7e04d666afd4c1573b4511bfd4ab53e0a931099658cde819bede29c7d8995b7134c6f0340a081536b07421eb6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
